### ISSUE TITLE
cy.kcFakeLogin is not a function

### ISSUE THREAD

**Issue by coolduebtn** [Fredx87/cypress-keycloak-commands#49]
Hello,
I am trying to implement the Fake Login for Integration testing 
I am using angular 12 and cypress 4.4.1

**I am done as described in the tutorial.**

- I have imported the line `import "cypress-keycloak-commands";` in commands.ts and hence there is no error while using the commands in the vscode editor.
- I have Setup the Keycloak configuration in cypress.json configuration file
- i have added the user token detail in the fixture file cypress/fixtures/users/user.json

when i run my e2e test, I get the following error when my cypress tests run 
`cy.kcFakeLogin is not a function`

Could you please help as I am stuck

**Comment by DasOhmoff** [comment]
I have the same issue. How did you fix it?

**Comment by DasOhmoff** [comment]
Oh. I got it already. Thanks
